### ISSUE TITLE
Content empty when logging enable

### ISSUE THREAD

**Issue by achretien** [AnytimeSA/anytime-api-php-sdk#2]
When logging is enabled at guzzle client level, the logger can read the content of the body.

Then because of stream usage, the pointer can already be at the end of the stream.

You should replace this line:

https://github.com/AnytimeSA/anytime-api-php-sdk/blob/1769a2d0ea16b0c698e0d81b948dd9b32d0ab2fd/src/IO/IO.php#L147

By:

`$this->responseParser->parse((string) $response->getBody())`

The __toString method rewind the Stream when the getContents one does not

https://github.com/guzzle/psr7/blob/1.4.2/src/Stream.php#L90

https://github.com/guzzle/psr7/blob/1.4.2/src/Stream.php#L100

**Comment by david-vde** [comment]
You are totally right. 

We will take this in account in the next update.

Kind regards
