### ISSUE TITLE
Exception when activation_date is null in cardInfo

### ISSUE THREAD

**Issue by achretien** [AnytimeSA/anytime-api-php-sdk#25]
It seems than the following field can be null in the API:

https://github.com/AnytimeSA/anytime-api-php-sdk/blob/master/src/Model/Response/Get/ModelResponseGetCardInfo.php#L28

In this case the `normalize` method throw an exception.

I think `getActivationDate` should return null if the field is null in the API

**Comment by david-vde** [comment]
Thank you. 

Its fixed in the v1.2.2 release.

**Comment by achretien** [comment]
not tagged correctly:

https://github.com/AnytimeSA/anytime-api-php-sdk/compare/v1.2.2...master

**Comment by david-vde** [comment]
Indeed. Fixed
